In [2]:
import pandas as pd

df = pd.read_csv('/home/gianluca/Research/datapruebas_analysis/data/raw/tmt/neuropruebas/subjects/facundoruiz2610@gmail.com-tmt-plugin_96.csv')
df.head(100)

,run_id,condition,success,timeout,failed_images,failed_audio,failed_video,trial_type,trial_index,time_elapsed,...,screen_id,recorded_at,ip,user_agent,device,browser,browser_version,platform,platform_version,source_code_version
0,96,1,true,false,[],[],[],preload,0,473,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
1,96,1,true,"""","""","""","""",fullscreen,1,5698,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
2,96,1,"""","""","""","""","""",survey-html-form,2,62104,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
3,96,1,"""","""","""","""","""",virtual-chinrest,3,359238,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
4,96,1,"""","""","""","""","""",instructions,4,451875,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
5,96,1,"""","""","""","""","""",html-keyboard-response,5,452380,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
6,96,1,"""","""","""","""","""",trail-making-test,6,477391,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
7,96,1,"""","""","""","""","""",html-keyboard-response,7,477898,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
8,96,1,"""","""","""","""","""",trail-making-test,8,502902,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
9,96,1,"""","""","""","""","""",instructions,9,521217,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
10,96,1,"""","""","""","""","""",html-keyboard-response,10,521718,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
11,96,1,"""","""","""","""","""",trail-making-test,11,545791,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
12,96,1,"""","""","""","""","""",html-keyboard-response,12,546293,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
13,96,1,"""","""","""","""","""",trail-making-test,13,571304,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
14,96,1,"""","""","""","""","""",html-keyboard-response,14,571806,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
15,96,1,"""","""","""","""","""",trail-making-test,15,593547,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
16,96,1,"""","""","""","""","""",html-keyboard-response,16,594048,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
17,96,1,"""","""","""","""","""",trail-making-test,17,619084,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
18,96,1,"""","""","""","""","""",html-keyboard-response,18,619586,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
19,96,1,"""","""","""","""","""",trail-making-test,19,644602,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
20,96,1,"""","""","""","""","""",html-keyboard-response,20,645104,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
21,96,1,"""","""","""","""","""",trail-making-test,21,670150,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
22,96,1,"""","""","""","""","""",html-keyboard-response,22,670652,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
23,96,1,"""","""","""","""","""",trail-making-test,23,691969,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
24,96,1,"""","""","""","""","""",html-keyboard-response,24,692469,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
25,96,1,"""","""","""","""","""",trail-making-test,25,717488,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
26,96,1,"""","""","""","""","""",html-keyboard-response,26,717989,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
27,96,1,"""","""","""","""","""",trail-making-test,27,738915,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
28,96,1,"""","""","""","""","""",html-keyboard-response,28,739416,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
29,96,1,"""","""","""","""","""",trail-making-test,29,764446,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
30,96,1,"""","""","""","""","""",html-keyboard-response,30,764947,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
31,96,1,"""","""","""","""","""",trail-making-test,31,789969,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
32,96,1,"""","""","""","""","""",html-keyboard-response,32,790472,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
33,96,1,"""","""","""","""","""",trail-making-test,33,815528,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
34,96,1,"""","""","""","""","""",html-keyboard-response,34,816030,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
35,96,1,"""","""","""","""","""",trail-making-test,35,841058,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
36,96,1,"""","""","""","""","""",html-keyboard-response,36,841560,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
37,96,1,"""","""","""","""","""",trail-making-test,37,865990,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
38,96,1,"""","""","""","""","""",html-keyboard-response,38,866492,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
39,96,1,"""","""","""","""","""",trail-making-test,39,890490,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
40,96,1,"""","""","""","""","""",html-keyboard-response,40,890993,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
41,96,1,"""","""","""","""","""",trail-making-test,41,914124,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
42,96,1,"""","""","""","""","""",html-keyboard-response,42,914626,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
43,96,1,"""","""","""","""","""",trail-making-test,43,939688,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
44,96,1,"""","""","""","""","""",html-keyboard-response,44,940191,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
45,96,1,"""","""","""","""","""",trail-making-test,45,962870,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
46,96,1,"""","""","""","""","""",html-keyboard-response,46,963373,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
47,96,1,"""","""","""","""","""",trail-making-test,47,982234,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
48,96,1,"""","""","""","""","""",html-keyboard-response,48,982736,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
49,96,1,"""","""","""","""","""",trail-making-test,49,986091,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
50,96,1,"""","""","""","""","""",survey-html-form,50,999977,...,Uso del pad,2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6
51,96,1,true,"""","""","""","""",fullscreen,51,1001011,...,"""",2021-09-23 17:30:43,190.195.149.159,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,WebKit,Chrome,93.0.4577.82,Windows,10.0,ecc94a16166beb1b2727fe3573fb85e6

In [3]:
df[['position', 'cursor_time', 'x_y_clicked_position', 'trial_type']]

,position,cursor_time,x_y_clicked_position,trial_type
0,"""","""","""",preload
1,"""","""","""",fullscreen
2,"""","""","[22,7,1603]",survey-html-form
3,"""","""","[171,75,9320]",virtual-chinrest
4,"""","""","""",instructions
5,"""","""","""",html-keyboard-response
6,"[""(477.9541218020757,552.7114763174109)"",""(474...","[11,26,490,506,987,995,1012,1028,1046,1062,108...","[469,668,1871]",trail-making-test
7,"""","""","""",html-keyboard-response
8,"[""(316.395383977137,508.3620160169734)"",""(316....","[122,160,210,264,443,460,477,494,510,529,543,5...","[429,108,2895]",trail-making-test
9,"""","""","""",instructions
10,"""","""","""",html-keyboard-response
11,"[""(363.9126598080013,582.8057529498507)"",""(378...","[706,714,724,741,758,773,791,808,824,841,857,8...","[646,342,1847]",trail-making-test
12,"""","""","""",html-keyboard-response
13,"[""(406.6782080557792,565.3827506889645)"",""(406...","[26,43,93,121,373,389,395,410,426,443,460,476,...","[284,130,1277]",trail-making-test
14,"""","""","""",html-keyboard-response
15,"[""(379.75175175162275,585.973571542739)"",""(381...","[325,479,625,640,660,709,725,740,757,773,790,8...","[635,606,3417]",trail-making-test
16,"""","""","""",html-keyboard-response
17,"[""(542.8943987709237,397.48836526587974)"",""(54...","[77,99,107,119,136,152,170,186,203,220,438,604...","[458,222,1385]",trail-making-test
18,"""","""","""",html-keyboard-response
19,"[""(348.07356786437987,549.5436577245225)"",""(34...","[180,208,212,227,244,264,286,388,404,444,461,4...","[474,659,2098]",trail-making-test
20,"""","""","""",html-keyboard-response
21,"[""(386.08738852907135,351.554995668998)"",""(384...","[9,13,34,50,65,66,83,99,150,166,182,199,215,23...","[240,245,2617]",trail-making-test
22,"""","""","""",html-keyboard-response
23,"[""(474.7863034133514,248.6008914001253)"",""(474...","[8,166,614,621,633,648,665,682,698,715,732,749...","[633,133,1547]",trail-making-test
24,"""","""","""",html-keyboard-response
25,"[""(395.5908436952442,213.75488687835298)"",""(40...","[58,74,91,108,124,140,204,546,557,575,591,609,...","[471,140,2201]",trail-making-test
26,"""","""","""",html-keyboard-response
27,"[""(571.4047642694422,254.9365285859021)"",""(569...","[67,77,95,185,227,245,262,287,327,344,361,423,...","[436,576,2319]",trail-making-test
28,"""","""","""",html-keyboard-response
29,"[""(344.90574947565557,438.6700069734288)"",""(34...","[3,186,200,217,239,256,272,284,856,867,885,900...","[612,582,2857]",trail-making-test
30,"""","""","""",html-keyboard-response
31,"[""(360.744841419277,544.7919298351899)"",""(360....","[192,432,446,458,474,491,515,524,838,846,857,8...","[606,668,4352]",trail-making-test
32,"""","""","""",html-keyboard-response
33,"[""(660.1036791537223,310.3733539614489)"",""(656...","[52,172,192,202,219,235,251,268,494,502,518,53...","[445,388,2140]",trail-making-test
34,"""","""","""",html-keyboard-response
35,"[""(313.2275655884127,299.28598888633957)"",""(31...","[4,15,33,49,66,83,100,116,134,150,208,216,232,...","[625,563,2697]",trail-making-test
36,"""","""","""",html-keyboard-response
37,"[""(534.9748527991129,533.7045647600805)"",""(534...","[86,118,134,151,168,184,200,218,235,251,267,28...","[517,237,3275]",trail-making-test
38,"""","""","""",html-keyboard-response
39,"[""(332.2344759207584,603.3965738036252)"",""(335...","[96,103,118,134,150,167,184,200,250,267,284,58...","[491,313,1867]",trail-making-test
40,"""","""","""",html-keyboard-response
41,"[""(547.64612635401,655.6655805862837)"",""(547.6...","[3,20,40,56,89,183,191,205,222,239,255,272,288...","[369,562,2340]",trail-making-test
42,"""","""","""",html-keyboard-response
43,"[""(656.935860764998,422.83091400898684)"",""(658...","[16,34,51,67,84,100,118,134,248,284,313,326,33...","[671,159,1779]",trail-making-test
44,"""","""","""",html-keyboard-response
45,"[""(143.74928179166324,517.8654717956385)"",""(15...","[59,75,92,108,125,142,159,175,192,208,225,242,...","[381,356,2615]",trail-making-test
46,"""","""","""",html-keyboard-response
47,"[""(579.324310241253,351.554995668998)"",""(577.7...","[4,156,163,179,195,212,229,245,262,284,340,353...","[178,227,1727]",trail-making-test
48,"""","""","""",html-keyboard-response
49,"[""(547.64612635401,414.91136752676584)"",""(547....","[17,34,51,71,238,331,368,416,425,467,484,501,5...","[423,617,3055]",trail-making-test
50,"""","""","[166,4,8379]",survey-html-form
51,"""","""","""",fullscreen

In [8]:
columns_of_interest = [str(i) for i in range(20)]
df[df['trial_type'] == 'trail-making-test'][['trial_type','position', 'cursor_time', 'x_y_clicked_position'] + columns_of_interest]

,trial_type,position,cursor_time,x_y_clicked_position,0,1,2,3,4,5,...,10,11,12,13,14,15,16,17,18,19
6,trail-making-test,"[""(477.9541218020757,552.7114763174109)"",""(474...","[11,26,490,506,987,995,1012,1028,1046,1062,108...","[469,668,1871]","{""content"":""1"",""x"":472,""y"":664}","{""content"":""2"",""x"":252,""y"":604}","{""content"":""3"",""x"":352,""y"":484}","{""content"":""4"",""x"":512,""y"":364}","{""content"":""5"",""x"":612,""y"":184}","{""content"":""6"",""x"":632,""y"":244}",...,"{""content"":""11"",""x"":157,""y"":449}","{""content"":""12"",""x"":197,""y"":369}","{""content"":""13"",""x"":112,""y"":424}","{""content"":""14"",""x"":172,""y"":584}","{""content"":""15"",""x"":292,""y"":444}","{""content"":""16"",""x"":232,""y"":504}","{""content"":""17"",""x"":392,""y"":344}","{""content"":""18"",""x"":292,""y"":484}","{""content"":""19"",""x"":412,""y"":384}","{""content"":""20"",""x"":372,""y"":244}"
8,trail-making-test,"[""(316.395383977137,508.3620160169734)"",""(316....","[122,160,210,264,443,460,477,494,510,529,543,5...","[429,108,2895]","{""content"":""1"",""x"":172,""y"":644}","{""content"":""A"",""x"":252,""y"":524}","{""content"":""2"",""x"":412,""y"":584}","{""content"":""B"",""x"":272,""y"":569}","{""content"":""3"",""x"":212,""y"":624}","{""content"":""C"",""x"":132,""y"":684}",...,"{""content"":""6"",""x"":332,""y"":404}","{""content"":""F"",""x"":512,""y"":504}","{""content"":""7"",""x"":652,""y"":344}","{""content"":""G"",""x"":532,""y"":204}","{""content"":""8"",""x"":472,""y"":124}","{""content"":""H"",""x"":592,""y"":284}","{""content"":""9"",""x"":492,""y"":204}","{""content"":""I"",""x"":432,""y"":104}","{""content"":""10"",""x"":332,""y"":264}","{""content"":""J"",""x"":232,""y"":284}"
11,trail-making-test,"[""(363.9126598080013,582.8057529498507)"",""(378...","[706,714,724,741,758,773,791,808,824,841,857,8...","[646,342,1847]","{""content"":""1"",""x"":652,""y"":344}","{""content"":""2"",""x"":632,""y"":204}","{""content"":""3"",""x"":512,""y"":284}","{""content"":""4"",""x"":397,""y"":124}","{""content"":""5"",""x"":452,""y"":284}","{""content"":""6"",""x"":352,""y"":124}",...,"{""content"":""11"",""x"":132,""y"":504}","{""content"":""12"",""x"":332,""y"":624}","{""content"":""13"",""x"":432,""y"":684}","{""content"":""14"",""x"":612,""y"":604}","{""content"":""15"",""x"":672,""y"":504}","{""content"":""16"",""x"":532,""y"":404}","{""content"":""17"",""x"":472,""y"":364}","{""content"":""18"",""x"":412,""y"":444}","{""content"":""19"",""x"":612,""y"":504}","{""content"":""20"",""x"":412,""y"":564}"
13,trail-making-test,"[""(406.6782080557792,565.3827506889645)"",""(406...","[26,43,93,121,373,389,395,410,426,443,460,476,...","[284,130,1277]","{""content"":""1"",""x"":292,""y"":124}","{""content"":""A"",""x"":172,""y"":124}","{""content"":""2"",""x"":252,""y"":304}","{""content"":""B"",""x"":492,""y"":224}","{""content"":""3"",""x"":352,""y"":344}","{""content"":""C"",""x"":512,""y"":444}",...,"{""content"":""6"",""x"":312,""y"":404}","{""content"":""F"",""x"":372,""y"":504}","{""content"":""7"",""x"":512,""y"":544}","{""content"":""G"",""x"":352,""y"":664}","{""content"":""8"",""x"":492,""y"":584}","{""content"":""H"",""x"":692,""y"":624}","{""content"":""9"",""x"":592,""y"":604}","{""content"":""I"",""x"":452,""y"":664}","{""content"":""10"",""x"":392,""y"":644}","{""content"":""J"",""x"":492,""y"":684}"
15,trail-making-test,"[""(379.75175175162275,585.973571542739)"",""(381...","[325,479,625,640,660,709,725,740,757,773,790,8...","[635,606,3417]","{""content"":""1"",""x"":632,""y"":604}","{""content"":""2"",""x"":572,""y"":664}","{""content"":""3"",""x"":532,""y"":564}","{""content"":""4"",""x"":592,""y"":524}","{""content"":""5"",""x"":672,""y"":484}","{""content"":""6"",""x"":492,""y"":524}",...,"{""content"":""11"",""x"":292,""y"":444}","{""content"":""12"",""x"":192,""y"":284}","{""content"":""13"",""x"":152,""y"":224}","{""content"":""14"",""x"":292,""y"":124}","{""content"":""15"",""x"":372,""y"":224}","{""content"":""16"",""x"":472,""y"":264}","{""content"":""17"",""x"":632,""y"":144}","{""content"":""18"",""x"":692,""y"":224}","{""content"":""19"",""x"":632,""y"":344}","{""content"":""20"",""x"":572,""y"":424}"
17,trail-making-test,"[""(542.8943987709237,397.48836526587974)"",""(54...","[77,99,107,119,136,152,170,186,203,220,438,604...","[458,222,1385]","{""content"":""1"",""x"":452,""y"":224}","{""content"":""A"",""x"":352,""y"":144}","{""content"":""2"",""x"":272,""y"":264}","{""content"":""B"",""x"":172,""y"":424}","{""content"":""3"",""x"":312,""y"":484}","{""content"":""C"",""x"":232,""y"":404}",...,"{""content"":""6"",""x"":557,""y"":504}","{""content"":""F"",""x"":692,""y"":604}","{""content"":""7"",""x"":512,""y"":549}","{""content"":""G"",""x"":412,""y"":564}","{""content"":""8"",""x"":272,""y"":684}","{""content"":""H"",""x"":152,""y"":664}","{""content"":""9"",""x"":292,""y"":564}","{""content"":""I"",""x"":232,""y"":624}","{""content"":""10"",""x"":337,""y"":544}","{""content"":""J"",""x"":212,""y"":669}"
19,trail-making-test,"[""(348.07356786437987,549.5436577245225)"",""(34...","[180,208,212,227,244,264,286,388,404,444,461,4...","[474,659,2098]","{""content"":""1"",""x"":472,""y"":664}","{""content"":""2"",""x"":252,""y"":604}","{""content"":""3"",""x"":352,""y"":484}","{""content"":""4"",""x"":512,""y"":364}","{""content"":""5"",""x"":612,""y"":184}","{""content"":""6"",""x"":632,""y"":244}",...,"{""content"":""11"",""x"":157,""y"":449}","{""content"":""12"",""x"":197,""y"":369}","{""content"":""13"",""x"":112,""y"":424}","{""content"":""14"",""x"":172,""y"":584}","{""content"":""15"",""x"":292,""y"":444}","{""content"":""16"",""x"":232,""y"":504}","{""content"":""17"",""x"":392,""y"":344}","{""content"":""18"",""x"":292,""y"":484}","{""content"":""19"",""x"":412,""y"":384}","{""content"":""20"",""x"":372,""y"":244}"
21,trail-making-test,"[""(386.08738852907135,351.554995668998)"",""(384...","[9,13,34,50,65,66,83,99,150,166,182,199,215,23...","[240,245,2617]","{""content"":""1"",""x"":252,""y"":244}","{""content"":""A"",""x"":372,""y"":284}","{""content"":""2"",""x"":412,""y"":244}","{""content"":""B"",""x"":352,""y"":344}","{""content"":""3"",""x"":252,""y"":564}","{""content"":""C"",""x"":152,""y"":644}",...,"{""content"":""6"",""x"":572,""y"":584}","{""content"":""F"",""x"":672,""y"":444}","{""content"":""7"",""x"":632,""y"":564}","{""content"":""G"",""x"":692,""y"":384}","{""content"":""8"",""x"":572,""y"":484}","{""content"":""H"",""x"":352,""y"":584}","{""content"":""9"",""x"":412,""y"":364}","{""content"":""I"",""x"":472,""y"":244}","{""content"":""10"",""x"":272,""y"":184}","{""content"":""J"",""x"":352,""y"":224}"
23,trail-making-test,"[""(474.7863034133514,248.6008914001253)"",""(474...","[8,166,614,621,633,648,665,682,698,715,732,749...","[633,133,1547]","{""content"":""1"",""x"":632,""y"":144}","{""content"":""2"",""x"":512,""y"":244}","{""content"":""3"",""x"":592,""y"":324}","{""content"":""4"",""x"":692,""y"":464}","{""content"":""5"",""x"":572,""y"":569}","{""content"":""6"",""x"":432,""y"":654}",...,"{""content"":""11"",""x"":292,""y"":624}","{""content"":""12"",""x"":372,""y"":484}","{""content"":""13"",""x"":472,""y"":524}","{""content"":""14"",""x"":572,""y"":484}","{""content"":""15"",""x"":492,""y"":384}","{""content"":""16"",""x"":432,""y"":304}","{""content"":""17"",""x"":312,""y"":204}","{""content"":""18"",""x"":152,""y"":164}","{""content"":""19"",""x"":252,""y"":144}","{""content"":""20"",""x"":352,""y"":164}"
25,trail-making-test,"[""(395.5908436952442,213.75488687835298)"",""(40...","[58,74,91,108,124,140,204,546,557,575,591,609,...","[471,140,2201]","{""content"":""1"",""x"":472,""y"":144}","{""content"":""A"",""x"":412,""y"":354}","{""content"":""2"",""x"":332,""y"":184}","{""content"":""B"",""x"":212,""y"":384}","{""content"":""3"",""x"":192,""y"":484}","{""content"":""C"",""x"":372,""y"":604}",...,"{""content"":""6"",""x"":652,""y"":524}","{""content"":""F"",""x"":512,""y"":464}","{""content"":""7"",""x"":392,""y"":404}","{""content"":""G"",""x"":532,""y"":344}","{""content"":""8"",""x"":612,""y"":224}","{""content"":""H"",""x"":672,""y"":144}","{""content"":""9"",""x"":572,""y"":264}","{""content"":""I"",""x"":432,""y"":304}","{""content"":""10"",""x"":572,""y"":204}","{""content"":""J"",""x"":472,""y"":284}"
27,trail-making-test,"[""(571.4047642694422,254.9365285859021)"",""(569...","[67,77,95,185,227,245,262,287,327,344,361,423,...","[436,576,2319]","{""content"":""1"",""x"":432,""y"":584}","{""content"":""2"",""x"":692,""y"":524}","{""content"":""3"",""x"":652,""y"":424}","{""content"":""4"",""x"":552,""y"":504}","{""content"":""5"",""x"":472,""y"":404}","{""content"":""6"",""x"":612,""y"":304}",...,"{""content"":""11"",""x"":232,""y"":604}","{""content"":""12"",""x"":212,""y"":504}","{""content"":""13"",""x"":152,""y"":424}","{""content"":""14"",""x"":112,""y"":364}","{""content"":""15"",""x"":212,""y"":244}","{""content"":""16"",""x"":292,""y"":124}","{""content"":""17"",""x"":252,""y"":184}","{""content"":""18"",""x"":192,""y"":284}","{""content"":""19"",""x"":157,""y"":384}","{""content"":""20"",""x"":172,""y"":329}"
29,trail-making-test,"[""(344.90574947565557,438.6700069734288)"",""(34...","[3,186,200,217,239,256,272,284,856,867,885,900...","[612,582,2857]","{""content"":""1"",""x"":612,""y"":584}","{""content"":""A"",""x"":672,""y"":504}","{""content"":""2"",""x"":572,""y"":604}","{""content"":""B"",""x"":372,""y"":644}","{""content"":""3"",""x"":472,""y"":524}","{""content"":""C"",""x"":612,""y"":404}",...,"{""content"":""6"",""x"":172,""y"":324}","{""content"":""F"",""x"":212,""y"":124}","{""content"":""7"",""x"":152,""y"":224}","{""content"":""G"",""x"":112,""y"":304}","{""content"":""8"",""x"":212,""y"":364}","{""content"":""H"",""x"":372,""y"":444}","{""content"":""9"",""x"":472,""y"":484}","{""content"":""I"",""x"":392,""y"":584}","{""content"":""10"",""x"":252,""y"":644}","{""content"":""J"",""x"":132,""y"":464}"
31,trail-making-test,"[""(360.744841419277,544.7919298351899)"",""(360....","[192,432,446,458,474,491,515,524,838,846,857,8...","[606,668,4352]","{""content"":""1"",""x"":612,""y"":664}","{""content"":""2"",""x"":652,""y"":564}","{""content"":""3"",""x"":612,""y"":384}","{""content"":""4"",""x"":472,""y"":304}","{""content"":""5"",""x"":432,""y"":444}","{""content"":""6"",""x"":312,""y"":344}",...,"{""content"":""11"",""x"":292,""y"":244}","{""content"":""12"",""x"":412,""y"":204}","{""content"":""13"",""x"":512,""y"":124}","{""content"":""14"",""x"":632,""y"":264}","{""content"":""15"",""x"":692,""y"":344}","{""content"":""16"",""x"":572,""y"":184}","{""content"":""17"",""x"":552,""y"":104}","{""content"":""18"",""x"":652,""y"":184}","{""content"":""19"",""x"":692,""y"":304}","{""content"":""20"",""x"":672,""y"":244}"
33,trail-making-test,"[""(660.1036791537223,310.3733539614489)"",""(656...","[52,172,192,202,219,235,251,268,494,502,518,53...","[445,388,2140]","{""content"":""1"",""x"":452,""y"":384}","{""content"":""A"",""x"":332,""y"":369}","{""content"":""2"",""x"":252,""y"":404}","{""content"":""B"",""x"":312,""y"":324}","{""content"":""3"",""x"":412,""y"":304}","{""content"":""C"",""x"":552,""y"":244}",...,"{""content"":""6"",""x"":612,""y"":444}","{""content"":""F"",""x"":472,""y"":484}","{""content"":""7"",""x"":372,""y"":664}","{""content"":""G"",""x"":212,""y"":544}","{""content"":""8"",""x"":112,""y"":604}","{""content"":""H"",""x"":192,""y"":384}","{""content"":""9"",""x"":252,""y"":164}","{""content"":""I"",""x"":312,""y"":244}","{""content"":""10"",""x"":412,""y"":164}","{""content"":""J"",""x"":292,""y"":289}"
35,trail-making-test,"[""(313.2275655884127,299.28598888633957)"",""(31...","[4,15,33,49,66,83,100,116,134,150,208,216,232,...","[625,563,2697]","{""content"":""1"",""x"":632,""y"":564}","{""content"":""2"",""x"":492,""y"":424}","{""content"":""3"",""x"":452,""y"":344}","{""content"":""4"",""x"":372,""y"":184}","{""content"":""5"",""x"":272,""y"":124}","{""content"":""6"",""x"":397,""y"":229}",...,"{""content"":""11"",""x"":152,""y"":444}","{""content"":""12"",""x"":112,""y"":684}","{""content"":""13"",""x"":212,""y"":624}","{""content"":""14"",""x"":372,""y"":444}","{""content"":""15"",""x"":512,""y"":544}","{""content"":""16"",""x"":372,""y"":624}","{""content"":""17"",""x"":412,""y"":584}","{""content"":""18"",""x"":472,""y"":524}","{""content"":""19"",""x"":417,""y"":629}","{""content"":""20"",""x"":292,""y"":564}"
37,trail-making-test,"[""(534.9748527991129,533.7045647600805)"",""(534...","[86,118,134,151,168,184,200,218,235,251,267,28...","[517,237,3275]","{""content"":""1"",""x"":512,""y"":244}","{""content"":""A"",""x"":632,""y"":124}","{""content"":""2"",""x"":492,""y"":104}","{""content"":""B"",""x"":552,""y"":184}","{""content"":""3"",""x"":452,""y"":124}","{""content"":""C"",""x"":372,""y"":264}",...,"{""content"":""6"",""x"":592,""y"":364}","{""content"":""F"",""x"":552,""y"":484}","{""content"":""7"",""x"":412,""y"":504}","{""content"":""G"",""x"":272,""y"":384}","{""content"":""8"",""x"":152,""y"":304}","{""content"":""H"",""x"":252,""y"":429}","{""content"":""9"",""x"":372,""y"":524}","{""content"":""I"",""x"":252,""y"":649}","{""content"":""10"",""x"":192,""y"":644}","{""content"":""J"",""x"":252,""y"":604}"
39,trail-making-test,"[""(332.2344759207584,603.3965738036252)"",""(335...","[96,103,118,134,150,167,184,200,250,267,284,58...","[491,313,1867]","{""content"":""1"",""x"":492,""y"":324}","{""content"":""2"",""x"":412,""y"":249}","{""content"":""3"",""x"":292,""y"":144}","{""content"":""4"",""x"":392,""y"":204}","{""content"":""5"",""x"":492,""y"":124}","{""content"":""6"",""x"":612,""y"":224}",...,"{""content"":""11"",""x"":152,""y"":404}","{""content"":""12"",""x"":252,""y"":524}","{""content"":""13"",""x"":372,""y"":444}","{""content"":""14"",""x"":512,""y"":429}","{""content"":""15"",""x"":692,""y"":364}","{""content"":""16"",""x"":512,""y"":544}","{""content"":""17"",""x"":332,""y"":624}","{""content"":""18"",""x"":432,""y"":584}","{""content"":""19"",""x"":552,""y"":544}","{""content"":""20"",""x"":512,""y"":664}"
41,trail-making-test,"[""(547.64612635401,655.6655805862837)"",""(547.6...","[3,20,40,56,89,183,191,205,222,239,255,272,288...","[369,562,2340]","{""content"":""1"",""x"":372,""y"":564}","{""content"":""A"",""x"":512,""y"":684}","{""content"":""2"",""x"":572,""y"":544}","{""content"":""B"",""x"":652,""y"":364}","{""content"":""3"",""x"":512,""y"":544}","{""content"":""C"",""x"":452,""y"":504}",...,"{""content"":""6"",""x"":312,""y"":384}","{""content"":""F"",""x"":372,""y"":284}","{""content"":""7"",""x"":472,""y"":184}","{""content"":""G"",""x"":612,""y"":164}","{""content"":""8"",""x"":672,""y"":224}","{""content"":""H"",""x"":532,""y"":264}","{""content"":""9"",""x"":432,""y"":344}","{""content"":""I"",""x"":372,""y"":424}","{""content"":""10"",""x"":492,""y"":324}","{""content"":""J"",""x"":672,""y"":414}"
43,trail-making-test,"[""(656.935860764998,422.83091400898684)"",""(658...","[16,34,51,67,84,100,118,134,248,284,313,326,33...","[671,159,1779]","{""content"":""1"",""x"":672,""y"":164}","{""content"":""2"",""x"":572,""y"":244}","{""content"":""3"",""x"":452,""y"":144}","{""content"":""4"",""x"":332,""y"":124}","{""content"":""5"",""x"":212,""y"":324}","{""content"":""6"",""x"":112,""y"":164}",...,"{""content"":""11"",""x"":402,""y"":604}","{""content"":""12"",""x"":242,""y"":504}","{""content"":""13"",""x"":292,""y"":584}","{""content"":""14"",""x"":412,""y"":664}","{""content"":""15"",""x"":352,""y"":624}","{""content"":""16"",""x"":232,""y"":544}","{""content"":""17"",""x"":172,""y"":624}","{""content"":""18"",""x"":132,""y"":524}","{""content"":""19"",""x"":192,""y"":484}","{""content"":""20"",""x"":152,""y"":574}"
45,trail-making-test,"[""(143.74928179166324,517.8654717956385)"",""(15...","[59,75,92,108,125,142,159,175,192,208,225,242,...","[381,356,2615]","{""content"":""1"",""x"":392,""y"":364}","{""content"":""A"",""x"":332,""y"":284}","{""content"":""2"",""x"":252,""y"":469}","{""content"":""B"",""x"":152,""y"":524}","{""content"":""3"",""x"":112,""y"":644}","{""content"":""C"",""x"":352,""y"":484}",...,"{""content"":""6"",""x"":592,""y"":524}","{""content"":""F"",""x"":692,""y"":584}","{""content"":""7"",""x"":592,""y"":444}","{""content"":""G"",""x"":432,""y"":344}","{""content"":""8"",""x"":612,""y"":384}","{""content"":""H"",""x"":632,""y"":304}","{""content"":""9"",""x"":692,""y"":144}","{""content"":""I"",""x"":512,""y"":204}","{""content"":""10"",""x"":432,""y"":244}","{""content"":""J"",""x"":402,""y"":284}"
47,trail-making-test,"[""(579.324310241253,351.554995668998)"",""(577.7...","[4,156,163,179,195,212,229,245,262,284,340,353...","[178,227,1727]","{""content"":""1"",""x"":172,""y"":224}","{""content"":""2"",""x"":272,""y"":304}","{""content"":""3"",""x"":152,""y"":484}","{""content"":""4"",""x"":252,""y"":364}","{""content"":""5"",""x"":192,""y"":504}","{""content"":""6"",""x"":132,""y"":584}",...,"{""content"":""11"",""x"":472,""y"":544}","{""content"":""12"",""x"":372,""y"":534}","{""content"":""13"",""x"":252,""y"":584}","{""content"":""14"",""x"":372,""y"":464}","{""content"":""15"",""x"":472,""y"":324}","{""content"":""16"",""x"":612,""y"":224}","{""content"":""17"",""x"":432,""y"":384}","{""content"":""18"",""x"":572,""y"":304}","{""content"":""19"",""x"":632,""y"":384}","{""content"":""20"",""x"":532,""y"":364}"
49,trail-making-test,"[""(547.64612635401,414.91136752676584)"",""(547....","[17,34,51,71,238,331,368,416,425,467,484,501,5...","[423,617,3055]","{""content"":""1"",""x"":392,""y"":604}","{""content"":""A"",""x"":492,""y"":644}","{""content"":""2"",""x"":392,""y"":504}","{""content"":""B"",""x"":292,""y"":404}","{""content"":""3"",""x"":152,""y"":324}","{""content"":""C"",""x"":252,""y"":224}",...,"{""content"":""6"",""x"":472,""y"":204}","{""content"":""F"",""x"":552,""y"":264}","{""content"":""7"",""x"":477,""y"":344}","{""content"":""G"",""x"":472,""y"":284}","{""content"":""8"",""x"":352,""y"":204}","{""content"":""H"",""x"":432,""y"":344}","{""content"":""9"",""x"":492,""y"":444}","{""content"":""I"",""x"":572,""y"":544}","{""content"":""10"",""x"":692,""y"":384}","{""content"":""J"",""x"":632,""y"":464}"

In [14]:
content1 = [{"content":"4","x":192,"y":484},{"content":"D","x":332,"y":364},{"content":"5","x":252,"y":444},{"content":"E","x":192,"y":529},{"content":"6","x":332,"y":404},{"content":"F","x":512,"y":504},{"content":"7","x":652,"y":344},{"content":"G","x":532,"y":204},{"content":"8","x":472,"y":124},{"content":"H","x":592,"y":284},{"content":"9","x":492,"y":204},{"content":"I","x":432,"y":104},{"content":"10","x":332,"y":264},{"content":"J","x":232,"y":284}]

In [16]:
content1

[{'content': '4', 'x': 192, 'y': 484},
 {'content': 'D', 'x': 332, 'y': 364},
 {'content': '5', 'x': 252, 'y': 444},
 {'content': 'E', 'x': 192, 'y': 529},
 {'content': '6', 'x': 332, 'y': 404},
 {'content': 'F', 'x': 512, 'y': 504},
 {'content': '7', 'x': 652, 'y': 344},
 {'content': 'G', 'x': 532, 'y': 204},
 {'content': '8', 'x': 472, 'y': 124},
 {'content': 'H', 'x': 592, 'y': 284},
 {'content': '9', 'x': 492, 'y': 204},
 {'content': 'I', 'x': 432, 'y': 104},
 {'content': '10', 'x': 332, 'y': 264},
 {'content': 'J', 'x': 232, 'y': 284}]