In [1]:
import pandas as pd

from src.config import METADATA_CSV, NEUROPRUEBAS_METADATA_PATH
from src.loader.metadata.datapruebas_metadata import add_datapruebas_metadata

metrics = pd.read_csv('/home/gianluca/Research/datapruebas_analysis/data/hand_analysis/2025-09-28_16-00-13/processed/tmt/neuropruebas/metrics.csv')

In [2]:
metrics

,subject_id,trial_id,trial_type,age,gender,is_valid,trial_order_of_appearance,speed_threshold,zigzag_amplitude,total_distance,...,max_duration,hesitation_periods,correct_targets_touches,wrong_targets_touches,number_of_crosses,distance_difference_from_ideal,area_difference_from_ideal,intra_target_time,inter_target_time,invalid_cause
0,df0b8572-3570-4c43-ac9b-017fec2adf22,NEUROPRUEBAS_0,PART_A,30,Masculino,True,0,0.280745,NaN,2961.443571,...,611.0,"[383, 184, 611, 265, 483, 160, 282, 433, 368, ...",19.0,0.0,NaN,15.102531,1138.783474,897.500000,1040.0,NaN
1,df0b8572-3570-4c43-ac9b-017fec2adf22,NEUROPRUEBAS_1,PART_B,30,Masculino,True,1,0.280745,-1683.800000,2004.264113,...,865.0,"[247, 136, 181, 647, 635, 334, 130, 649, 692, ...",12.0,0.0,NaN,19.965649,1167.949561,1974.181818,1909.0,NaN
2,df0b8572-3570-4c43-ac9b-017fec2adf22,NEUROPRUEBAS_2,PART_A,30,Masculino,True,2,0.280745,NaN,602.764093,...,2181.0,"[115, 349, 2181]",3.0,1.0,NaN,66.469884,1159.167441,761.000000,3661.0,NaN
3,df0b8572-3570-4c43-ac9b-017fec2adf22,NEUROPRUEBAS_3,PART_B,30,Masculino,True,3,0.280745,-2619.666667,2216.741478,...,6432.0,"[1000, 735, 267, 4181, 1205, 6432]",7.0,0.0,NaN,200.659486,6170.363070,2501.833333,7359.0,NaN
4,df0b8572-3570-4c43-ac9b-017fec2adf22,NEUROPRUEBAS_4,PART_A,30,Masculino,True,4,0.280745,NaN,3082.300046,...,1813.0,"[572, 502, 832, 832, 261, 183, 598, 1049, 200,...",18.0,0.0,NaN,33.621124,2458.406010,1261.058824,870.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5515,c0a70c2c-6409-4176-9264-781f4dce88db,NEUROPRUEBAS_15,PART_B,30,Masculino,True,15,0.469468,-915.000000,2201.171429,...,1067.0,"[1067, 50, 267, 217, 66, 33, 516, 283, 299, 16...",14.0,0.0,NaN,25.387806,1643.536474,1477.538462,2006.0,NaN
5516,c0a70c2c-6409-4176-9264-781f4dce88db,NEUROPRUEBAS_16,PART_A,30,Masculino,False,16,0.469468,NaN,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNKNOWN_ERROR
5517,c0a70c2c-6409-4176-9264-781f4dce88db,NEUROPRUEBAS_17,PART_B,30,Masculino,True,17,0.469468,-808.600000,3892.574991,...,4766.0,"[350, 50, 134, 67, 166, 84, 233, 233, 531, 283...",12.0,8.0,NaN,101.606203,4655.807135,1257.545455,8461.0,NaN
5518,c0a70c2c-6409-4176-9264-781f4dce88db,NEUROPRUEBAS_18,PART_A,30,Masculino,True,18,0.469468,NaN,3594.205571,...,1783.0,"[49, 134, 83, 276, 141, 750, 33, 300, 100, 299...",20.0,0.0,NaN,47.783338,2239.000763,1059.631579,308.0,NaN
5519,c0a70c2c-6409-4176-9264-781f4dce88db,NEUROPRUEBAS_19,PART_B,30,Masculino,True,19,0.469468,-375.000000,3176.367260,...,12616.0,"[149, 17, 633, 866, 649, 12616, 1284, 600]",6.0,13.0,NaN,18.148148,1215.555371,886.200000,18055.0,NaN

In [3]:
from src.config import DATAPRUEBAS_METADATA_PATH

metadata = pd.read_csv(NEUROPRUEBAS_METADATA_PATH, sep=';')

In [4]:
metadata

,username,last_log,email,is_active,id,genero,nivel_educativo,nacionalidad,pais_de_residencia,año_de_nacimiento,puntos,consentimiento
0,daniela,NaN,danielamacab@gmail.com,f,87e81627-5b5e-43e0-af23-61d82151d73d,F,S,Argentina,Argentina,1992.0,0.0,t
1,dani,NaN,danimacab@gmail.com,f,fdf5eb50-1131-4488-8dfe-3527a5565854,F,S,Argentina,Argentina,1992.0,0.0,t
2,dani1234,NaN,danielamacab@yahoo.com.ar,f,b0a8c5b5-fb0e-413c-b4fc-50fe832c4709,F,S,Argentina,Argentina,1992.0,0.0,t
3,Guanel,2022-05-08 15:37:57.117458+00,caceresnaguel@gmail.com,t,c2030111-c98e-4a81-b7e8-36058ba9dd0f,M,P,Argentina,Argentina,1988.0,0.0,t
4,Kyrem,2022-03-16 00:00:40.319897+00,ivodiazalejandro@gmail.com,t,48885748-ffa9-49c4-b864-dd6817560b1c,M,S,Argentino,Italia,2000.0,0.0,t
...,...,...,...,...,...,...,...,...,...,...,...,...
740,Mjmorteruiz,2022-11-05 20:06:10.117142+00,mjmorteruiz@hotmail.com,t,cd02ab0d-8291-4857-92f8-b3bdf3cbff97,F,U,Española,España,1967.0,0.0,t
741,ccmartincc,2022-11-01 14:53:21.419309+00,correamartin270@gmail.com,t,e900d33a-cdf9-4ba4-9eed-e22cf1ffb44d,M,S,Argentina,Argentina,2002.0,0.0,t
742,Luciasecin,2022-11-01 16:51:59.12705+00,luciasecin@gmail.com,t,36cd7267-798c-4489-8e63-b4c7bb0df688,F,T,Argentina,Argentina,1999.0,0.0,t
743,lucassg,2022-11-09 15:02:50.016241+00,lucasservi@gmail.com,t,4283b2f7-c357-487e-a484-9a15b8f2300b,M,U,Argentina,Argentina,1992.0,0.0,t
744,Maruycleo,2022-12-02 02:09:19.509206+00,maruycleo@hotmail.com,t,49b5a2f7-0318-4c6b-babc-b0f1fd71eef5,F,U,Argentina,Argentina,1987.0,0.0,t

In [5]:
metadata.columns

Index(['username', 'last_log', 'email', 'is_active', 'id', 'genero',
       'nivel_educativo', 'nacionalidad', 'pais_de_residencia',
       'año_de_nacimiento', 'puntos', 'consentimiento'],
      dtype='object')

In [6]:
# Convertir a str y minúsculas para evitar problemas de tipos y mayúsculas
subject_vals = metrics['subject_id'].astype(str).str.lower()
mail_vals = metadata['email'].astype(str).str.lower()

# Contar cuántos aparecen en df2.mail
count = subject_vals.isin(mail_vals).sum()
count

0

In [10]:
metadata[metadata['email'] =='marialaraa@gmail.com']

Empty DataFrame
Columns: [username, last_log, email, is_active, id, genero, nivel_educativo, nacionalidad, pais_de_residencia, año_de_nacimiento, puntos, consentimiento]
Index: []

In [11]:
from src.loader.metadata.neuropruebas_metadata import add_neuropruebas_metadata

metrics = pd.read_csv(
        '/home/gianluca/Research/datapruebas_analysis/data/hand_analysis/2025-09-28_16-00-13/processed/tmt/neuropruebas/metrics.csv')
nuevo_df, metadata_errors = add_neuropruebas_metadata(metrics, subject_col='subject_id')

WARNING:root:No se encontró metadata para subject_id: facundoruiz2610@gmail.com-tmt-plugin_96.csv
WARNING:root:No se encontró metadata para subject_id: 9BkUDGTRoXgEwNpUnzBLRb
WARNING:root:No se encontró metadata para subject_id: lena.peroni@gmail.com-tmt-plugin_146.csv
WARNING:root:No se encontró metadata para subject_id: leandrogori2000@gmail.com-tmt-plugin_112.csv
WARNING:root:No se encontró metadata para subject_id: dFUWGq7kzJpxH9DbUTf6DU
WARNING:root:No se encontró metadata para subject_id: marialaraa@gmail.com-tmt-plugin_125.csv
WARNING:root:No se encontró metadata para subject_id: ign.alonso94@gmail.com-tmt-plugin_173.csv
WARNING:root:No se encontró metadata para subject_id: nkRpekDDdAvFmBdSjfWW9G
WARNING:root:No se encontró metadata para subject_id: gonzalocagnola@gmail.com-tmt-plugin_167.csv
WARNING:root:No se encontró metadata para subject_id: Kh7tJGF8xwkk6eQWcCC9cB
WARNING:root:No se encontró metadata para subject_id: KustqtPzkoKa74j4Hug7bP
WARNING:root:No se encontró metadata para subject_id: NiuaaS7BnV9vJWJsrx8VQf
WARNING:root:No se encontró metadata para subject_id: 8LPCw6HSWAYUDNmMTYGGc4
WARNING:root:No se encontró metadata para subject_id: alejandrohacker42@gmail.com-tmt-plugin_98.csv
WARNING:root:No se encontró metadata para subject_id: axelgualdoni@hotmail.com-tmt-plugin_137.csv
WARNING:root:No se encontró metadata para subject_id: josefinamercedescaso@gmail.com-tmt-plugin_147.csv
WARNING:root:No se encontró metadata para subject_id: cienarte11@gmail.com-tmt-plugin_136.csv
WARNING:root:No se encontró metadata para subject_id: 2FY3LCdaQWkSv6xuejuFDp
WARNING:root:No se encontró metadata para subject_id: sheinsherman@hotmail.com-tmt-plugin_128.csv
WARNING:root:No se encontró metadata para subject_id: marianoagoca@gmail.com-tmt-plugin_97.csv
WARNING:root:No se encontró metadata para subject_id: caro.alberca@gmail.com-tmt-plugin_94.csv
WARNING:root:No se encontró metadata para subject_id: riosruizsara@gmail.com-tmt-plugin_138.csv
WARNING:root:No se encontró metadata para subject_id: mbrassesco@dc.uba.ar-tmt-plugin_148.csv
WARNING:root:No se encontró metadata para subject_id: fernandezlarrosanicolas@gmail.com-tmt-plugin_116.csv
WARNING:root:No se encontró metadata para subject_id: davidaclausell@gmail.com-tmt-plugin_133.csv
WARNING:root:No se encontró metadata para subject_id: jonathanspaccarotella@gmail.com-tmt-plugin_131.csv
WARNING:root:No se encontró metadata para subject_id: melaniefanara@hotmail.com-tmt-plugin_103.csv
WARNING:root:No se encontró metadata para subject_id: shima.carolina@gmail.com-tmt-plugin_121.csv
WARNING:root:No se encontró metadata para subject_id: danielalucianaprina@gmail.com-tmt-plugin_171.csv
WARNING:root:No se encontró metadata para subject_id: agostinastahl@yahoo.com-tmt-plugin_106.csv
WARNING:root:No se encontró metadata para subject_id: HKraBZKnkqG4BpuPaBSR24
WARNING:root:No se encontró metadata para subject_id: solvarelag4@gmail.com-tmt-plugin_101.csv
WARNING:root:No se encontró metadata para subject_id: facundo.linari@hotmail.com-tmt-plugin_141.csv
WARNING:root:No se encontró metadata para subject_id: gastonbujia@gmail.com-tmt-plugin_107.csv
WARNING:root:No se encontró metadata para subject_id: damianos.care@gmail.com-tmt-plugin_111.csv
WARNING:root:No se encontró metadata para subject_id: leonardodpepino@gmail.com-tmt-plugin_124.csv
WARNING:root:No se encontró metadata para subject_id: Na6sPyZEPtaW9eHyDUocaX
WARNING:root:No se encontró metadata para subject_id: mvillalbadavoli@gmail.com-tmt-plugin_95.csv
WARNING:root:No se encontró metadata para subject_id: nicolasfigueroagarcia@gmail.com-tmt-plugin_99.csv
WARNING:root:No se encontró metadata para subject_id: constanzafperez@gmail.com-tmt-plugin_104.csv
WARNING:root:No se encontró metadata para subject_id: sofia.rodriguezseijo@gmail.com-tmt-plugin_117.csv
WARNING:root:No se encontró metadata para subject_id: MSu6zAyysfFqnZq9VVJcAC
WARNING:root:No se encontró metadata para subject_id: catalinalepesc@gmail.com-tmt-plugin_162.csv
WARNING:root:No se encontró metadata para subject_id: elholm90@gmail.com-tmt-plugin_180.csv
WARNING:root:No se encontró metadata para subject_id: 8DVnWrAr5yaN9uFKBjUwQD

In [21]:
nuevo_df[nuevo_df['subject_id'] == '8DVnWrAr5yaN9uFKBjUwQD']

,subject_id,trial_id,trial_type,age,gender,is_valid,trial_order_of_appearance,speed_threshold,zigzag_amplitude,total_distance,...,number_of_crosses,distance_difference_from_ideal,area_difference_from_ideal,intra_target_time,inter_target_time,invalid_cause,birth_date,gender,education_level,nationality
5380,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_0,PART_A,30,Masculino,True,0,0.463459,NaN,3532.755219,...,NaN,24.651078,1359.333471,583.333333,1738.0,NaN,NaN,None,None,None
5381,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_1,PART_B,30,Masculino,False,1,0.463459,NaN,0.000000,...,NaN,NaN,NaN,NaN,NaN,UNKNOWN_ERROR,NaN,None,None,None
5382,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_2,PART_A,30,Masculino,True,2,0.463459,NaN,2611.902510,...,NaN,15.993720,1380.713518,571.615385,3014.0,NaN,NaN,None,None,None
5383,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_3,PART_B,30,Masculino,True,3,0.463459,-1883.166667,4034.754184,...,NaN,156.567135,5977.272183,1620.538462,2521.0,NaN,NaN,None,None,None
5384,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_4,PART_A,30,Masculino,True,4,0.463459,NaN,4333.951468,...,NaN,73.241637,3259.760176,894.666667,1266.0,NaN,NaN,None,None,None
5385,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_5,PART_B,30,Masculino,False,5,0.463459,NaN,0.000000,...,NaN,NaN,NaN,NaN,NaN,UNKNOWN_ERROR,NaN,None,None,None
5386,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_6,PART_A,30,Masculino,True,6,0.463459,NaN,2763.178827,...,NaN,18.154183,1294.434883,664.055556,466.0,NaN,NaN,None,None,None
5387,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_7,PART_B,30,Masculino,True,7,0.463459,-1001.750000,3530.688959,...,NaN,48.196459,3541.096325,1296.352941,1448.0,NaN,NaN,None,None,None
5388,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_8,PART_A,30,Masculino,True,8,0.463459,NaN,3365.317747,...,NaN,49.311306,1283.757974,607.736842,438.0,NaN,NaN,None,None,None
5389,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_9,PART_B,30,Masculino,True,9,0.463459,-753.333333,3141.043021,...,NaN,26.657063,1069.842572,965.888889,756.0,NaN,NaN,None,None,None
5390,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_10,PART_A,30,Masculino,True,10,0.463459,NaN,4326.757774,...,NaN,87.892045,4860.108641,903.157895,315.0,NaN,NaN,None,None,None
5391,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_11,PART_B,30,Masculino,True,11,0.463459,-646.222222,3623.574818,...,NaN,50.233015,2789.545863,1038.947368,488.0,NaN,NaN,None,None,None
5392,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_12,PART_A,30,Masculino,True,12,0.463459,NaN,3681.368842,...,NaN,33.675043,2678.004669,706.444444,1473.0,NaN,NaN,None,None,None
5393,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_13,PART_B,30,Masculino,True,13,0.463459,-1069.111111,3240.786007,...,NaN,43.776086,1629.085990,884.000000,935.0,NaN,NaN,None,None,None
5394,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_14,PART_A,30,Masculino,True,14,0.463459,NaN,3306.454130,...,NaN,26.818434,1190.155082,849.894737,372.0,NaN,NaN,None,None,None
5395,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_15,PART_B,30,Masculino,True,15,0.463459,-651.777778,3410.311021,...,NaN,42.108972,1841.543734,929.157895,536.0,NaN,NaN,None,None,None
5396,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_16,PART_A,30,Masculino,True,16,0.463459,NaN,3289.059177,...,NaN,37.408444,2182.759017,850.842105,315.0,NaN,NaN,None,None,None
5397,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_17,PART_B,30,Masculino,True,17,0.463459,-1229.250000,3378.598297,...,NaN,55.179065,1835.603038,1173.705882,689.0,NaN,NaN,None,None,None
5398,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_18,PART_A,30,Masculino,True,18,0.463459,NaN,3203.583006,...,NaN,26.759259,1500.459208,635.777778,620.0,NaN,NaN,None,None,None
5399,8DVnWrAr5yaN9uFKBjUwQD,NEUROPRUEBAS_19,PART_B,30,Masculino,True,19,0.463459,-813.444444,2948.238981,...,NaN,26.099952,1476.244976,921.578947,387.0,NaN,NaN,None,None,None