In [1]:
import pandas as pd

from src.config import METADATA_CSV
from src.loader.metadata.datapruebas_metadata import add_datapruebas_metadata

metrics = pd.read_csv('/home/gianluca/Research/datapruebas_analysis/data/hand_analysis/2025-09-28_16-00-13/processed/tmt/datapruebas/metrics.csv')

In [2]:
metrics

,subject_id,trial_id,trial_type,age,gender,is_valid,trial_order_of_appearance,speed_threshold,zigzag_amplitude,total_distance,...,max_duration,hesitation_periods,correct_targets_touches,wrong_targets_touches,number_of_crosses,distance_difference_from_ideal,area_difference_from_ideal,intra_target_time,inter_target_time,invalid_cause
0,7b1760b5-1341-4b27-bd4c-432e231c5fad,DATAPRUEBAS_0,PART_A,30,M,True,0,0.650362,NaN,3223.912544,...,593.0,"[593, 102, 250, 79, 141, 531, 78, 16, 125, 297...",19.0,0.0,NaN,21.855360,933.954479,759.388889,1536.0,NaN
1,7b1760b5-1341-4b27-bd4c-432e231c5fad,DATAPRUEBAS_1,PART_B,30,M,True,1,0.650362,-1556.500000,2683.409160,...,1466.0,"[125, 469, 627, 453, 484, 199, 62, 721, 1466, ...",13.0,1.0,NaN,49.882631,2363.093028,1718.916667,2786.0,NaN
2,7b1760b5-1341-4b27-bd4c-432e231c5fad,DATAPRUEBAS_2,PART_A,30,M,True,2,0.650362,NaN,2580.015061,...,453.0,"[26, 95, 191, 31, 32, 140, 133, 61, 453, 125, ...",19.0,0.0,NaN,11.182113,847.023337,611.277778,970.0,NaN
3,7b1760b5-1341-4b27-bd4c-432e231c5fad,DATAPRUEBAS_3,PART_B,30,M,True,3,0.650362,-707.333333,3130.738759,...,977.0,"[141, 17, 125, 550, 47, 500, 109, 296, 141, 62...",20.0,1.0,NaN,20.453797,1316.977908,1027.157895,1441.0,NaN
4,7b1760b5-1341-4b27-bd4c-432e231c5fad,DATAPRUEBAS_4,PART_A,30,M,True,4,0.650362,NaN,3717.713472,...,3093.0,"[16, 16, 329, 234, 344, 1172, 94, 3093, 1289, ...",19.0,1.0,NaN,56.055264,3180.571701,1244.000000,661.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,aba4756b-4bb0-41a5-b76b-2e8d6d406491,DATAPRUEBAS_15,PART_B,30,M,True,15,0.267679,-1242.000000,2055.778386,...,4504.0,"[534, 267, 83, 99, 283, 4021, 4504, 3420]",6.0,6.0,NaN,20.539635,1523.576845,1164.200000,14943.0,NaN
1096,aba4756b-4bb0-41a5-b76b-2e8d6d406491,DATAPRUEBAS_16,PART_A,30,M,True,16,0.267679,NaN,2122.970534,...,2152.0,"[117, 50, 133, 84, 217, 234, 584, 685, 334, 2152]",13.0,1.0,NaN,24.297336,2429.782292,1587.416667,443.0,NaN
1097,aba4756b-4bb0-41a5-b76b-2e8d6d406491,DATAPRUEBAS_17,PART_B,30,M,True,17,0.267679,-1416.000000,1904.253872,...,6239.0,"[784, 84, 367, 133, 660, 6239, 568, 1384]",3.0,4.0,NaN,198.173742,13714.187328,3694.000000,14574.0,NaN
1098,aba4756b-4bb0-41a5-b76b-2e8d6d406491,DATAPRUEBAS_18,PART_A,30,M,True,18,0.267679,NaN,127.642365,...,0.0,[],2.0,0.0,NaN,5.516768,296.176902,716.000000,191.0,NaN
1099,aba4756b-4bb0-41a5-b76b-2e8d6d406491,DATAPRUEBAS_19,PART_B,30,M,True,19,0.267679,-1000.500000,741.806556,...,4035.0,"[434, 66, 429, 151, 4035]",5.0,1.0,NaN,19.702967,1218.933242,1020.500000,6899.0,NaN

In [3]:
from src.loader.metadata.datapruebas_metadata import add_datapruebas_metadata
df2 = add_datapruebas_metadata(metrics)
df2.head()

,subject_id,trial_id,trial_type,age,gender,is_valid,trial_order_of_appearance,speed_threshold,zigzag_amplitude,total_distance,...,area_difference_from_ideal,intra_target_time,inter_target_time,invalid_cause,birth_date,gender,education_level,nationality,country_of_residence,region_of_residence
0,5df915f3-cc1a-4469-9a5c-93206bd4954f,DATAPRUEBAS_0,PART_A,30,M,True,0,0.279711,NaN,147.264952,...,592.366441,623.000000,183.0,NaN,1989-11-05,Masculino,Universitaria completa,Argentina,Argentina,Ciudad Autónoma de Buenos Aires
1,5df915f3-cc1a-4469-9a5c-93206bd4954f,DATAPRUEBAS_1,PART_B,30,M,True,1,0.279711,-4946.0,913.816653,...,2100.996995,3838.000000,2456.0,NaN,1989-11-05,Masculino,Universitaria completa,Argentina,Argentina,Ciudad Autónoma de Buenos Aires
2,5df915f3-cc1a-4469-9a5c-93206bd4954f,DATAPRUEBAS_2,PART_A,30,M,True,2,0.279711,NaN,2588.958200,...,1135.987054,1098.000000,866.0,NaN,1989-11-05,Masculino,Universitaria completa,Argentina,Argentina,Ciudad Autónoma de Buenos Aires
3,5df915f3-cc1a-4469-9a5c-93206bd4954f,DATAPRUEBAS_3,PART_B,30,M,True,3,0.279711,-1447.8,1816.299326,...,2464.132719,1757.700000,5236.0,NaN,1989-11-05,Masculino,Universitaria completa,Argentina,Argentina,Ciudad Autónoma de Buenos Aires
4,5df915f3-cc1a-4469-9a5c-93206bd4954f,DATAPRUEBAS_4,PART_A,30,M,True,4,0.279711,NaN,2852.708424,...,2747.562199,1413.466667,1108.0,NaN,1989-11-05,Masculino,Universitaria completa,Argentina,Argentina,Ciudad Autónoma de Buenos Aires

In [4]:
from src.config import DATAPRUEBAS_METADATA_PATH

metadata = pd.read_csv(DATAPRUEBAS_METADATA_PATH)

In [5]:
metadata.columns

Index(['Id sujeto', 'Id ejecucion', 'Estado', 'Fecha de nacimiento', 'Género',
       'Nivel educativo', 'Nacionalidad', 'Pais de residencia',
       'Región de residencia'],
      dtype='object')